name: MapleSEA Updates Watcher

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '.github/workflows/watcher.yml'

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Download previous storage file
      uses: actions/download-artifact@v3
      continue-on-error: true
      with:
        name: seen-posts-storage
        path: .

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run MapleSEA updates check
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        CHECK_INTERVAL_MINUTES: 5
      run: |
        python main.py check

    - name: Upload storage file
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: seen-posts-storage
        path: seen_posts.json
        retention-days: 30